#!/usr/bin/env python3
"""
build_full_bundle.py — Empaqueta TODOS los archivos del proyecto LeadX en un único .md descargable.
Genera /home/z/my-project/download/LEADX_CODIGO_COMPLETO.md
"""
from pathlib import Path
from datetime import datetime, timezone, timedelta
import subprocess

OUT = Path("/home/z/my-project/download/LEADX_CODIGO_COMPLETO.md")
REPO = Path("/tmp/leadx_repo")

FILES = [
    ("worker.js", "javascript",
     "Cloudflare Worker v3 — HTML embebido + 20+ endpoints API + CRM dashboard + cron edge. "
     "Incluye: normalizePhoneAR() con 27 códigos de área AR, getUrlSecret() con sessionStorage+auto-prompt+fallback 'LEGACY_SECRET_REMOVED', "
     "validateWaFromModal() abre WhatsApp directo con window.open(waUrl) sin Apify, /api/whatsapp-validate con webhookUrl fire & forget, "
     "/api/whatsapp-webhook recibe resultados async, /api/apify-facebook con webhookUrl, /api/apify-webhook con regex AR phones+emails+merge KV, "
     "pinned leads (12 curados), WhatsApp SVG icons, heat score 0-100."),
    ("generate_payload.py", "python",
     "Pipeline Python (GH Actions cada 1h). Incluye: scrape_ventafe_leads() con 5 páginas (?p=N) + URLs reales del aviso "
     "(/automoviles/5011376-honda-hr-v-...), normalize_ar_phone_ventafe(), filtros PAIN_KEYWORDS_RE con "
     "excepción VentaFe + keywords preventivas ('papeles al día', 'listo para transferir'), "
     "scoring con bypass para VentaFe (umbrales 40/25 + has_contact, no requiere has_explicit_pain), "
     "dedup por URL+teléfono (estable entre runs), mine_comments_for_contacts(), "
     "enrich_contacts_via_reddit_profile(), detector de contradicciones (vendedor miente + deuda real), "
     "clasific.ar quirúrgico (solo score>=70 + patente, campo deuda_clasificar), ML Questions num=50."),
    ("search_providers.py", "python",
     "Providers: Reddit /search.rss (Atom feed) con html.unescape(), Facebook via DDG, ForoArgentina, "
     "MercadoLibre Q&A. Blacklist de subreddits irrelevantes. Rotación de 10 queries."),
    ("source_registry.py", "python",
     "Registro de fuentes y rotación de queries."),
    ("pending_queries_kv.py", "python",
     "Helper para persistir queries pendientes en KV (rotación cuando Reddit devuelve 429)."),
    ("generate_payload_old_zai.py", "python",
     "Versión legacy del pipeline usando z-ai web_search (backup, no se usa en producción)."),
    ("wrangler.toml", "toml",
     "Config Cloudflare Worker — KV binding LEADX_KV + cron trigger `0 * * * *` (cada 1h)."),
    (".github/workflows/radar-cron.yml", "yaml",
     "GitHub Actions — cron cada 1h. Steps: checkout → setup python → install z-ai CLI → run pipeline → "
     "commit JSONs → POST /api/ingest al Worker → deploy Worker."),
    ("README.md", "markdown", "Documentación del proyecto."),
    ("dashboard_payload.schema.json", "json", "Schema del payload que consume el dashboard."),
    ("crm_dashboard.html", "html",
     "HTML estático del CRM (referencia, el worker.js tiene el embebido actualizado)."),
]

def get_repo_file(rel_path: str) -> str:
    p = REPO / rel_path
    if not p.exists():
        return f"[ARCHIVO NO ENCONTRADO: {rel_path}]"
    return p.read_text(encoding="utf-8", errors="replace")

def git_log_oneline(n: int = 20) -> str:
    try:
        r = subprocess.run(
            ["git", "-C", str(REPO), "log", "--oneline", f"-{n}"],
            capture_output=True, text=True, timeout=10,
        )
        return r.stdout.strip()
    except Exception:
        return "(no se pudo obtener git log)"

def build():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    log = git_log_oneline(20)
    lines = []
    lines.append("# 📦 LeadX — Código Completo (Bundle Único)")
    lines.append("")
    lines.append(f"**Generado:** {now}  ")
    lines.append(f"**Repo:** https://github.com/simonkey888/Leadx  ")
    lines.append(f"**Deploy:** https://leadx.simondalmasso44.workers.dev  ")
    lines.append(f"**Stack:** Cloudflare Worker (edge) + Python GH Actions (scoring) + KV storage  ")
    lines.append(f"**Worker Version:** 315cea94-45cb-464a-a056-850cc52817da  ")
    lines.append(f"**Estado:** Producción activa · 9 leads FB Grupo A · 8 con botón Messenger azul en tabla · score_explain + contact_confidence · pipeline 4.0 · rediseño Twenty.com")
    lines.append(f"**Timestamp generación:** {now} (hora UTC) · Argentina: {datetime.now(timezone(timedelta(hours=-3))).strftime('%Y-%m-%d %H:%M:%S')} ART")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📋 Índice de Archivos")
    lines.append("")
    lines.append("| # | Archivo | Líneas | Descripción |")
    lines.append("|---|---------|--------|-------------|")
    for i, (rel, _, desc) in enumerate(FILES, 1):
        content = get_repo_file(rel)
        n = content.count("\n") + 1
        lines.append(f"| {i} | `{rel}` | {n:,} | {desc} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 🏗️ Arquitectura")
    lines.append("")
    lines.append("```")
    lines.append("┌─────────────────────────────────────────────────────────────┐")
    lines.append("│  GITHUB ACTIONS (cron cada 1h)                              │")
    lines.append("│  ┌─────────────────────────────────────────────────────┐   │")
    lines.append("│  │ generate_payload.py                                 │   │")
    lines.append("│  │  1. scrape_ventafe_leads()  → VentaFe 5 paginas     │   │")
    lines.append("│  │     • URL real del aviso: /automoviles/ID-slug      │   │")
    lines.append("│  │     • normalize_ar_phone_ventafe()                  │   │")
    lines.append("│  │     • time.sleep(3) entre paginas (?p=N)            │   │")
    lines.append("│  │  2. search_reddit()         → /search.rss (Atom)    │   │")
    lines.append("│  │  2b. ML Questions num=50   → /api/ml-questions       │   │")
    lines.append("│  │  3. extract_entities()      → phone/patent/persona  │   │")
    lines.append("│  │     • PAIN_KEYWORDS_RE + excepción VentaFe          │   │")
    lines.append("│  │  4. classify_and_score()    → heat 0-100            │   │")
    lines.append("│  │     • VentaFe: umbrales 40/25 + has_contact         │   │")
    lines.append("│  │     • Otras fuentes: 50/30 + has_explicit_pain      │   │")
    lines.append("│  │  4.5 clasific.ar QUIRURGICO (solo score>=70+patente)│   │")
    lines.append("│  │     • agrega campo deuda_clasificar al Lead         │   │")
    lines.append("│  │  5. dedup by URL+teléfono (estable entre runs)      │   │")
    lines.append("│  │  6. POST /api/ingest → Worker (deep merge por ID)   │   │")
    lines.append("│  └─────────────────────────────────────────────────────┘   │")
    lines.append("└──────────────────────────────┬──────────────────────────────┘")
    lines.append("                               │")
    lines.append("                               ▼")
    lines.append("┌─────────────────────────────────────────────────────────────┐")
    lines.append("│  CLOUDFLARE WORKER (edge IP, cron cada 1h)                  │")
    lines.append("│  ┌─────────────────────────────────────────────────────┐   │")
    lines.append("│  │ worker.js                                           │   │")
    lines.append("│  │  • CRM HTML embebido (single file)                  │   │")
    lines.append("│  │  • getUrlSecret() → sessionStorage + auto-prompt    │   │")
    lines.append("│  │    + fallback hardcoded 'LEGACY_SECRET_REMOVED'                  │   │")
    lines.append("│  │  • validateWaFromModal() → window.open(waUrl)       │   │")
    lines.append("│  │    (ABRE WHATSAPP DIRECTO, sin Apify)               │   │")
    lines.append("│  │  • normalizePhoneAR() → 27 códigos de área AR       │   │")
    lines.append("│  │  • /api/leads         GET  → lista paginada          │   │")
    lines.append("│  │  • /api/ingest        POST → deep merge por ID       │   │")
    lines.append("│  │  • /api/cron-run      GET  → scraping Reddit+VentaFe │   │")
    lines.append("│  │  • /api/enrich-all    GET  → clasific.ar + OSINT     │   │")
    lines.append("│  │  • /api/shadow-osint  GET  → Linktree Hunter         │   │")
    lines.append("│  │  • /api/ventafe-debug GET  → debug HTML VentaFe      │   │")
    lines.append("│  │  • /api/whatsapp-validate POST → fire & forget       │   │")
    lines.append("│  │    con webhookUrl → Apify llama a webhook solo       │   │")
    lines.append("│  │  • /api/whatsapp-webhook POST → recibe resultados    │   │")
    lines.append("│  │    async de Apify, guarda en KV con TTL 24h          │   │")
    lines.append("│  │  • /api/apify-facebook POST → scraea grupos FB       │   │")
    lines.append("│  │    con cookies refrescables + webhookUrl             │   │")
    lines.append("│  │  • /api/apify-webhook POST → recibe posts FB         │   │")
    lines.append("│  │    extrae AR phones + emails + merge por ID en KV    │   │")
    lines.append("│  │  • Pinned leads (12 curados primeros)                │   │")
    lines.append("│  └─────────────────────────────────────────────────────┘   │")
    lines.append("│           │                                                 │")
    lines.append("│           ▼                                                 │")
    lines.append("│  ┌─────────────────────────────────────────────────────┐   │")
    lines.append("│  │ KV: LEADX_KV (leads + history + pinned)             │   │")
    lines.append("│  │   INGEST_SECRET = 'LEGACY_SECRET_REMOVED' (sincronizado GH+CF)    │   │")
    lines.append("│  │   wa_val:PHONE → resultados WhatsApp (TTL 24h)       │   │")
    lines.append("│  │   fb_cookies → cookies Facebook refrescables         │   │")
    lines.append("│  └─────────────────────────────────────────────────────┘   │")
    lines.append("└─────────────────────────────────────────────────────────────┘")
    lines.append("                               │")
    lines.append("                               ▼")
    lines.append("  Frontend read-only: leadx.simondalmasso44.workers.dev")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## ✅ Fixes Aplicados (Historia Reciente)")
    lines.append("")
    lines.append("### BOMBA #1 — WhatsApp Unauthorized → FIXED")
    lines.append("- `getUrlSecret()` ahora usa `sessionStorage` (persistente por tab)")
    lines.append("- Auto-prompt pide la clave la primera vez que se carga el dashboard")
    lines.append("- Fallback hardcoded `'LEGACY_SECRET_REMOVED'` como última línea para que la UI nunca quede en read-only")
    lines.append("- Worker `INGEST_SECRET` seteado a `'LEGACY_SECRET_REMOVED'` via `wrangler secret put`")
    lines.append("- GitHub Actions secret `INGEST_SECRET` también actualizado a `'LEGACY_SECRET_REMOVED'` via API")
    lines.append("")
    lines.append("### BOMBA #2 — Filtrado se comía leads VentaFe → FIXED (4 partes)")
    lines.append("")
    lines.append("| # | Punto del pipeline | Antes | Después |")
    lines.append("|---|---|---|---|")
    lines.append("| 1 | `VEHICULAR_KEYWORDS_STRICT` (l.~750) | `has_contact` siempre False porque los teléfonos se extraían DESPUÉS del check | Bypass directo para `is_ventafe` |")
    lines.append("| 2 | `PAIN_KEYWORDS_RE` (l.~826) | Regex muy estricto, no incluía 'papeles al día', 'listo para transferir' | Ampliado + excepción explícita VentaFe |")
    lines.append("| 3 | `classify_and_score` (l.~1197) | `has_explicit_pain` no incluía keywords preventivas → VentaFe caía en `reject` | Ampliado + bypass del penalty -50 para VentaFe |")
    lines.append("| 4 | `deduplicate_cases` (l.~1322) | Todos los leads VentaFe compartían `source_url` → dedup los colapsaba en 1 | URL única real del aviso + composite incluye teléfono |")
    lines.append("")
    lines.append("### FIX QWEN #1 — URLs VentaFe genéricas → FIXED")
    lines.append("- Scraper ahora extrae el `href` real del HTML de cada aviso")
    lines.append("- Cada lead VentaFe tiene URL única clickeable tipo `https://www.ventafe.com.ar/automoviles/4859456-toyota-corolla-2-0-xei-cvt-2025-0klm`")
    lines.append("- `aviso_id` disponible como campo para enriquecimiento futuro (cruce con clasific.ar)")
    lines.append("- Fallback por teléfono solo si no encuentra el href")
    lines.append("")
    lines.append("### FIX QWEN #2 — WhatsApp validate fallaba con Apify → FIXED (OPCIÓN A)")
    lines.append("- `validateWaFromModal()` ya NO llama a `/api/whatsapp-validate`")
    lines.append("- Ahora hace `window.open(waUrl, '_blank')` directo → abre WhatsApp en nueva pestaña")
    lines.append("- Construye `_wa_url` al vuelo si falta (fallback con `_wa_e164`)")
    lines.append("- Marca el lead como `validated_whatsapp` localmente (persistido en localStorage)")
    lines.append("- Endpoint `/api/whatsapp-validate` queda como legacy (no se rompe) pero el frontend ya no lo llama")
    lines.append("")
    lines.append("### FIX QWEN P0 — 3 fixes críticos → DONE")
    lines.append("")
    lines.append("**#1 — `/api/whatsapp-validate` con webhookUrl (fire & forget puro):**")
    lines.append("- Antes: lanzaba run Apify SIN `webhookUrl` → resultado perdido")
    lines.append("- Ahora: pasa `webhookUrl=${origin}/api/whatsapp-webhook` como query param → Apify llama al webhook automáticamente cuando termina")
    lines.append("- Sin polling, sin CPU timeout")
    lines.append("- Test: API devuelve `\"webhook_configured\":true` ✓")
    lines.append("")
    lines.append("**#2 — `/api/apify-facebook` + `/api/apify-webhook` (ya estaba implementado):**")
    lines.append("- Qwen estaba mirando una versión vieja del código")
    lines.append("- `/api/apify-facebook` ya pasa `webhookUrl` en el body (commit anterior)")
    lines.append("- `/api/apify-webhook` ya existe con regex de teléfonos AR + emails + merge por ID en KV")
    lines.append("")
    lines.append("**#3 — `classify_and_score` umbrales relajados para VentaFe:**")
    lines.append("- Branch separado en `classify_and_score()`:")
    lines.append("  - VentaFe: `score >= 40 + has_contact → real_lead` / `score >= 25 + has_contact → commercial_signal`")
    lines.append("  - Otras fuentes (Reddit/FB/ML): mantienen umbrales estrictos originales (50/30 con `has_explicit_pain`)")
    lines.append("- VentaFe ya NO requiere `has_explicit_pain` para clasificar como lead válido")
    lines.append("")
    lines.append("### Estado final del KV (verificado)")
    lines.append("")
    lines.append("| Métrica | Antes | Qwen P0 | v2.7 | v2.9 | Audit v5 | Sabueso F1+F2 |")
    lines.append("|---|---|---|---|---|---|---|")
    lines.append("| Total leads en KV | 53 | 80 | 117 | 117 | 32 | **6** |")
    lines.append("| Calidad de leads | ❌ Basura | 🟡 Mixta | 🟡 Mixta | 🟡 Mixta | 🟡 Mixta | **🟢 Todos preventivos reales** |")
    lines.append("| Leads con teléfono | 1 | 28 | 45 | 45 | 32 | **6 (100%)** |")
    lines.append("| Leads con WhatsApp link | 1 | 27 | 44 | 44 | 32 | **6 (100%)** |")
    lines.append("| Botón WhatsApp funcional | ❌ Unauthorized | ✅ wa.me | ✅ | ✅ | ✅ | **✅** |")
    lines.append("| Scraper VentaFe | 1 pág | 1 pág | 5 págs (45) | 5 págs (45) | 5 págs (45) | **5 págs (44)** |")
    lines.append("| Filtro VentaFe 'Pain o Patente' | ❌ | ❌ | ❌ | ❌ | ❌ | **✅ Admisión + Salida** |")
    lines.append("| Bug '08' → '308' falso positivo | ❌ | ❌ | ❌ | ❌ | ❌ | **✅ \\b08\\b** |")
    lines.append("| Score inflado por 'transferir' suelto | ❌ | ❌ | ❌ | ❌ | ❌ | **✅ Traba/bloqueo requerido** |")
    lines.append("| Filtros frontend defaults | 3 | 3 | 3 | 5 | 5 (todos) | **5 (todos)** |")
    lines.append("| Auth frontend | ❌ prompt | ✅ | ✅ | ✅ Sin prompt | ✅ Sin prompt | **✅ Sin prompt** |")
    lines.append("| Reddit SOLO Argentina | ❌ | ❌ | ❌ | ✅ Python | ✅ Python+Edge | **✅** |")
    lines.append("| Edge Cron TDZ fix | ❌ | ❌ | ❌ | ❌ | ❌ | **✅** |")
    lines.append("| Decay temporal (>7d) | ❌ | ❌ | ❌ | ❌ | ✅ | **✅** |")
    lines.append("| Validación cruzada área↔prov | ❌ | ❌ | ❌ | ❌ | ✅ | **✅ (-10 pts)** |")
    lines.append("| Encoding 'transferencia' | ❌ | ❌ | ❌ | ❌ | ✅ html.unescape | **✅** |")
    lines.append("| Persona única VentaFe | ❌ | ❌ | ❌ | ❌ | ✅ Vendedor #ID | **✅** |")
    lines.append("| KPI Total casos = bandeja | ❌ | ❌ | ❌ | ❌ | ✅ Alineados | **✅** |")
    lines.append("")
    lines.append("### FIX QWEN v2.7 — Escala real (3 cambios) → DONE")
    lines.append("")
    lines.append("**#1 — VentaFe paginación 5 páginas:**")
    lines.append("- Antes: solo página 1 (~100 bloques, 17 leads)")
    lines.append("- Ahora: itera 5 páginas con `?p=N` (NO `?page=N` que devuelve siempre página 1)")
    lines.append("- `time.sleep(3)` entre páginas para no saturar")
    lines.append("- Resultado: 500 bloques → 45 leads extraídos por run (vs 17 antes)")
    lines.append("")
    lines.append("**#2 — ML Questions num=50:**")
    lines.append("- Antes: `search_mercadolibre_questions(num=15)`")
    lines.append("- Ahora: `search_mercadolibre_questions(num=50)`")
    lines.append("- Aprovecha el endpoint `/api/ml-questions` del Worker que bypassea 403 de ML")
    lines.append("")
    lines.append("**#3 — clasific.ar quirúrgico:**")
    lines.append("- Antes: enriquecía TODOS los leads con PATENTE_DETECTED (gastaba 200/mes rápido)")
    lines.append("- Ahora: solo si `score >= 70` AND `PATENTE_DETECTED` (200/mes rinden mucho más)")
    lines.append("- Agregado campo `deuda_clasificar` al dataclass Lead para mostrar en modal")
    lines.append("- Rate limit aumentado a 1s entre consultas (era 0.5s)")
    lines.append("")
    lines.append("### FIX QWEN v2.8 — 3 fixes urgentes → DONE")
    lines.append("")
    lines.append("**#1 — URLs VentaFe con 3 estrategias en cascada:**")
    lines.append("- Antes: solo extraía href real del HTML (muy restrictivo)")
    lines.append("- Ahora: 3 estrategias en cascada:")
    lines.append("  1. `href` real del HTML (lo más confiable — VentaFe ya arma el slug correcto)")
    lines.append("  2. Construir URL desde `#ID` del bloque + slug del título (nuevo)")
    lines.append("  3. Anchor por teléfono (último recurso)")
    lines.append("")
    lines.append("**#2 — Filtros frontend (sidebar) — 7 filtros nuevos:**")
    lines.append("- Nueva sección **Contacto**: Todos / Con WhatsApp / Con Email / Sin contacto")
    lines.append("- Nueva sección **Temperatura**: Todos / 🔥 Calientes / ⚡ Tibios / ⚪ Fríos")
    lines.append("- `S.contactFilter` y `S.heatFilter` en el state object")
    lines.append("- `filterContact()` y `filterHeat()` funciones nuevas")
    lines.append("- `applyFilters()` extendido con `cf` y `hf` (8 líneas nuevas)")
    lines.append("- `renderCounts()` extendido con 8 contadores nuevos (cnt-whatsapp, cnt-hot, etc.)")
    lines.append("- Icono SVG de WhatsApp verde en el filtro 'Con WhatsApp'")
    lines.append("")
    lines.append("**#3 — Filtros anti-basura (gaming + USA):**")
    lines.append("- `GAMING_KEYWORDS` (30+ keywords: playstation, xbox, gta, steam, etc.)")
    lines.append("- `GAMING_SUBREDDITS` (20+ subreddits: gaming, gamingargentina, playstation, etc.)")
    lines.append("- `REJECT_IF_CONTAINS.extend(GAMING_KEYWORDS)`")
    lines.append("- `FOREIGN_INDICATORS` extendido con `USA` (paypal, venmo, zelle, [usa-*, [h], [w]) y `Gaming`")
    lines.append("- `extract_entities()` filtra subreddits de gaming (return None)")
    lines.append("- `extract_entities()` filtra posts con 2+ keywords de gaming (return None)")
    lines.append("")
    lines.append("### FIX QWEN v2.9 — Sin prompt auth + Reddit SOLO Argentina → DONE")
    lines.append("")
    lines.append("**#1 — Eliminar prompt de autenticación (worker.js):**")
    lines.append("- Eliminado el IIFE que pedía la clave con `prompt()` al cargar el dashboard")
    lines.append("- `getUrlSecret()` ahora siempre devuelve `'LEGACY_SECRET_REMOVED'` hardcodeado")
    lines.append("- Sin `sessionStorage` ni URL params necesarios")
    lines.append("- Dashboard abre directo sin pedir nada (uso interno, frontend read-only)")
    lines.append("- Nota de seguridad: si en el futuro se necesita auth real, agregar allowlist de IPs o proxy en el Worker")
    lines.append("")
    lines.append("**#2 — Filtro Reddit SOLO Argentina (generate_payload.py):**")
    lines.append("- En `classify_and_score()`: si `platform=Reddit` Y no hay señal AR explícita en el texto")
    lines.append("  (`has_arg_signal=False` y ninguna AR keyword extra), descartar el lead inmediatamente con `return None`")
    lines.append("- AR keywords extra: 25+ (argentina, BS AS, CABA, córdoba, santa fe, rosario, mendoza,")
    lines.append("  entre ríos, neuquén, salta, la plata, arba, dnrpa, rentas, pba, gba, parana, tigre,")
    lines.append("  avellaneda, quilmes, moron, pilar, etc.)")
    lines.append("- En `collect_public_sources()`: forzar `'argentina'` en queries Reddit con f-string segura")
    lines.append("  (evita dobles espacios y queries mal formadas)")
    lines.append("- Resultado: cero leads Reddit de Italia/USA/genéricos llegan al CRM")
    lines.append("- Los leads Reddit viejos del KV envejecen naturalmente (deep merge los conserva pero no se renuevan)")
    lines.append("")
    lines.append("### FIX GEMINI AUDIT v3 — sourceFilter case-insensitive + PLATFORM_MAP VentaFe → DONE")
    lines.append("")
    lines.append("**#1 — PLATFORM_MAP en generate_payload.py:**")
    lines.append("- Agregado `'ventafe.com.ar': 'VentaFe'` y `'www.ventafe.com.ar': 'VentaFe'` al diccionario")
    lines.append("- Antes Python hacía `host.title()` produciendo `'Ventafe.Com.Ar'` (inconsistente con filtro)")
    lines.append("- Ahora asigna `'VentaFe'` directamente, sin caer al fallback `.title()`")
    lines.append("")
    lines.append("**#2 — sourceFilter case-insensitive + substring match en worker.js:**")
    lines.append("- Antes: `(l.source_label || '') !== sf` → fallaba con `'Ventafe.Com.Ar' !== 'VentaFe'`")
    lines.append("- Ahora: `leadSrc.includes(filterSrc) || filterSrc.includes(leadSrc)` (case-insensitive)")
    lines.append("- Funciona incluso si los leads viejos del KV todavía tienen `'Ventafe.Com.Ar'` como source_label")
    lines.append("")
    lines.append("### FIX GEMINI AUDIT v4 — Defaults filtros a 'todos' → DONE")
    lines.append("")
    lines.append("- Antes: `sourceFilter='VentaFe'` + `contactFilter='whatsapp'` + `heatFilter='hot'` por defecto")
    lines.append("- Solo 2 leads cumplían los 3 criterios simultáneamente → tabla mostraba 2 mientras KPI decía 33")
    lines.append("- Ahora: los 3 filtros arrancan en `'todos'`. Botones HTML `'active'` en `'Todos'`.")
    lines.append("- Sergio puede filtrar manualmente después si quiere segmentar.")
    lines.append("")
    lines.append("### FIX VISUAL — Encoding 'tran ferencia' + Persona única → DONE")
    lines.append("")
    lines.append("**#1 — Encoding 'tran ferencia' (generate_payload.py scrape_ventafe_leads):**")
    lines.append("- Antes: `_re.sub(r'&[a-z]+;', ' ', text)` reemplazaba TODAS las entidades HTML con espacio")
    lines.append("  rompiendo palabras como `'transferencia'` → `'tran ferencia'` (entidades `&#101;` en el medio)")
    lines.append("- Ahora: `html.unescape()` ANTES del regex de limpieza para decodificar entidades correctamente")
    lines.append("- Resultado: 0 leads con `'tran ferencia'`, encoding correcto.")
    lines.append("")
    lines.append("**#2 — Persona única por lead VentaFe:**")
    lines.append("- Antes: todos los leads tenían `username='Vendedor VentaFe'` y `author='Vendedor VentaFe'` (indistinguibles)")
    lines.append("- Ahora: cada lead tiene `persona_label = 'Vendedor #{aviso_id}'` (ej: `'Vendedor #5011376'`)")
    lines.append("  o `'Vendedor tel …1234'` como fallback")
    lines.append("- Sergio puede ver cuál es cuál en la tabla.")
    lines.append("")
    lines.append("### FIX GEMINI AUDIT v5 — KPI Total casos = bandeja → DONE")
    lines.append("")
    lines.append("- Antes: `applyFilters()` tenía 2 filtros extras ocultos:")
    lines.append("  - `if (resumenLow.includes('lead vehicular') || ...) return false;`")
    lines.append("  - `if (!l.provincia && !l.pinned) return false;` ← ESTE mataba 29 leads (la mayoría de VentaFe no tiene provincia)")
    lines.append("- KPI decía 32 pero la tabla mostraba 3 (los 29 restantes caían en el filtro oculto)")
    lines.append("- Ahora: `applyFilters()` solo aplica los filtros de la sidebar (status, prov, source, contact, heat, search)")
    lines.append("- Resultado: KPI `'Total casos'` = número de filas en bandeja. Siempre.")
    lines.append("")
    lines.append("### FIX GEMINI AUDIT v3-EDGE — Edge Cron Reddit SOLO AR + fix TDZ VentaFe → DONE")
    lines.append("")
    lines.append("**#1 — Edge Cron Reddit SOLO Argentina (worker.js runPipelineCron):**")
    lines.append("- El Edge Cron del Worker NO tenía el filtro AR estricto que sí existe en `classify_and_score` del Python")
    lines.append("- Traía 17 leads Reddit basura (portugués, sin señal AR, sin teléfono)")
    lines.append("- Agregado filtro: si no hay keyword AR explícita, descartar el lead")
    lines.append("- Adicional: requiere `painKwStrict` (multa/transferencia/deuda/patente/libre deuda — no solo 'auto/moto' genérico)")
    lines.append("- `junkKw` extendido: lovecraft, meteorito, paysandu, gaming, playstation, xbox")
    lines.append("")
    lines.append("**#2 — Bug TDZ en scraper VentaFe del Edge Cron:**")
    lines.append("- `vfHtml` se usaba en línea 3245 ANTES de ser declarado en línea 3254 (Temporal Dead Zone)")
    lines.append("- El scraper VentaFe del Edge Cron fallaba silenciosamente")
    lines.append("- Movido `const vfHtml = await vfRes.text()` ANTES del primer uso")
    lines.append("")
    lines.append("**#3 — Paginación VentaFe del Edge Cron:**")
    lines.append("- Usaba `?page=` (que NO pagina en VentaFe, devuelve siempre página 1)")
    lines.append("- Cambiado a `?p=` (paginación real, misma que el Python)")
    lines.append("")
    lines.append("### FIX GEMINI EXTRA — Decay temporal + Validación cruzada geo + Fix duplicado → DONE")
    lines.append("")
    lines.append("**#1 — Decay temporal en /api/ingest (worker.js):**")
    lines.append("- Leads con estado `'Nuevo'` (o sin estado) que tienen >7 días de antigüad pierden 5 pts de score por día extra")
    lines.append("- Recalcula `_heat_label` automáticamente (hot/warm/cold)")
    lines.append("- Solo aplica a leads NO gestionados (no toca Contactado/En gestión/Cerrado)")
    lines.append("")
    lines.append("**#2 — Validación cruzada código de área vs provincia (generate_payload.py classify_and_score):**")
    lines.append("- Si teléfono empieza con 342 (Santa Fe) pero provincia dice 'Córdoba', marcar signal `ORIGEN_MISMATCH`")
    lines.append("- Penalización: -10 al score")
    lines.append("- Mapa: 342/341=Santa Fe, 351=Córdoba, 261=Mendoza, 221=Buenos Aires, 11=CABA, 381=Tucumán, 299=Neuquén")
    lines.append("")
    lines.append("**#3 — Eliminar llamada duplicada a scrape_ventafe_leads (generate_payload.py):**")
    lines.append("- Estaba llamada 2 veces en `collect_public_sources` (líneas 757 y 766)")
    lines.append("- Cada llamada scrapea 5 páginas con `sleep(3)` = 15s extra perdido")
    lines.append("- Ahora se llama 1 sola vez. Pipeline 15s más rápido.")
    lines.append("")
    lines.append("### FIX GEMINI AUDIT v6 — TDZ score + ReferenceError ventafeLeads → DONE")
    lines.append("")
    lines.append("**#1 — TDZ (Temporal Dead Zone) en runPipelineCron (worker.js):**")
    lines.append("- Línea 3289 (vieja): `score += 10` → usaba `score` ANTES de declararlo")
    lines.append("- Línea 3291 (vieja): `let score = 40` → declaración después del uso")
    lines.append("- Causaba `ReferenceError: Cannot access 'score' before initialization` cada vez que el Edge Cron procesaba un aviso VentaFe")
    lines.append("- Fix: mover `let score = 40` ANTES del primer uso de `score`")
    lines.append("")
    lines.append("**#2 — ReferenceError `ventafeLeads` (worker.js):**")
    lines.append("- Línea 3313 (vieja): `console.log('[CRON] VentaFe done: ' + ventafeLeads.length + ...)`")
    lines.append("- La variable `ventafeLeads` no existe en ese scope (solo se usa `newLeads`)")
    lines.append("- Causaba crash al final del scraper VentaFe del Edge Cron")
    lines.append("- Fix: reemplazar `ventafeLeads` por `newLeads`")
    lines.append("")
    lines.append("### FIX GEMINI SABUESO Fase 1 — Filtro de Calidad de Dos Vías VentaFe → DONE")
    lines.append("")
    lines.append("**Problema:** El CRM mostraba avisos comunes de VentaFe (Peugeot 308 limpio) como leads con dolor.")
    lines.append("")
    lines.append("**Causa raíz — Bug del 'Peugeot 308':**")
    lines.append("- El filtro `MUST_INCLUDE_ONE` tenía `'08'` suelto, y el regex matcheaba `'08'` dentro de `'308'`, `'2016'`, `'110.000km'`")
    lines.append("- Regalaba +40 pts falsos por `document_08` a avisos que no mencionaban formulario 08")
    lines.append("")
    lines.append("**3 parches quirúrgicos:**")
    lines.append("")
    lines.append("**Paso 1 — Matar bug '08' (3 puntos):**")
    lines.append("- Removido `'08'` de `MUST_INCLUDE_ONE` (ahora solo palabras reales)")
    lines.append("- `extract_entities`: `has_must_match` usa `re.search(r'\\b08\\b', text)`")
    lines.append("- `classify_and_score`: `'08' in text` → `re.search(r'\\b08\\b', text)`")
    lines.append("- `problem_category`: mismo fix")
    lines.append("")
    lines.append("**Paso 2 — Filtro de Admisión VentaFe (Pain o Patente):**")
    lines.append("- Al inicio de `classify_and_score`: si es VentaFe, solo pasa si tiene dolor textual explícito (multa/deuda/infraccion/etc) O patente declarada")
    lines.append("- Avisos comunes sin dolor ni patente → `return None`")
    lines.append("")
    lines.append("**Paso 3 — Filtro de Salida en `run_pipeline` (post-clasific.ar):**")
    lines.append("- Después del Step 4.5 (enriquecimiento clasific.ar), si un lead VentaFe no tiene dolor textual Y `deuda_clasificar=0`, se descarta")
    lines.append("- Log: `[Sabueso Descarte] Lead X eliminado: sin dolor textual y deuda=0`")
    lines.append("")
    lines.append("**Resultado Fase 1:** bajó de 44 a 6 leads (86% de ruido eliminado). Pero 4 de los 6 eran falsos positivos por `'transferir'` suelto.")
    lines.append("")
    lines.append("### FIX GEMINI SABUESO Fase 2 — Afinación fina eliminar falsos positivos → DONE")
    lines.append("")
    lines.append("**Problema Fase 1:** 4 de 6 leads eran falsos positivos porque el scoring daba +45 pts a cualquier aviso que mencionara `'transferir'` o `'transferencia'` (95% de avisos comunes de VentaFe usan esas palabras en contexto comercial, no de dolor).")
    lines.append("")
    lines.append("**2 parches quirúrgicos:**")
    lines.append("")
    lines.append("**Punto A — Refinar filtro de admisión VentaFe:**")
    lines.append("- Lista de keywords expandida con términos compuestos de alto valor preventivo:")
    lines.append("  - `patente paga`, `patentes pagas`, `patente al dia`")
    lines.append("  - `sin deudas`, `sin multas`, `libre de multas`")
    lines.append("  - `08 vencido`, `titular fallecido`, `no tengo el 08`")
    lines.append("  - `transferencia inmediata`, `se transfiere si o si`, `se transfiere sí o sí`")
    lines.append("- Confirmado: NO se admiten `'transferencia'` o `'transferir'` sueltas (solo frases compuestas)")
    lines.append("")
    lines.append("**Punto B — Evitar inflación de score por transferencia común:**")
    lines.append("- Antes: cualquier mención de `'transferir/transferencia'` daba +45 pts")
    lines.append("- Ahora: si es VentaFe Y no hay palabras de traba/bloqueo")
    lines.append("  (`no puedo`, `problema`, `traba`, `bloqueo`, `demora`, `embargo`, `no se puede`, `impedimento`, `inhibicion`)")
    lines.append("  NO se suman los +45 pts")
    lines.append("- Para Reddit/FB/ML sigue sumando normal (no tienen contexto comercial)")
    lines.append("")
    lines.append("**Resultado Fase 2:** 6 leads en CRM, **TODOS preventivos reales**:")
    lines.append("- Mercedes A200 — 'sin deuda, multas, etc.'")
    lines.append("- Peugeot 208 2022 — 'Listo para transferir. Patente paga 2026, sin multas' ⭐")
    lines.append("- Grand Vitara — 'PAPELES AL DIA' ⭐")
    lines.append("- Ford Ka 2007 — 'listo para transferir'")
    lines.append("- Peugeot 208 2021 — 'papeles al dia'")
    lines.append("- Peugeot 206 — 'Listo para transferir'")
    lines.append("")
    lines.append("### FIX GEMINI SABUESO v3 — Bug masivo de ortografía 's' desaparecidas → DONE")
    lines.append("")
    lines.append("**Problema crítico — La letra 's' desapareció del CRM:**")
    lines.append("- 'Disputa' → 'Di puta'")
    lines.append("- 'transferencia' → 'tran ferencia'")
    lines.append("- 'Mercedes' → 'Mercede '")
    lines.append("- 'hasta' → 'ha ta'")
    lines.append("- 'pesos' → 'pe o '")
    lines.append("- 'usado' → 'u ado'")
    lines.append("- 'estado' → 'e tado'")
    lines.append("")
    lines.append("**Causa raíz:**")
    lines.append("- El template literal `DASHBOARD_HTML` en worker.js (líneas 19-1632) usa backticks")
    lines.append("- Dentro de un template literal, `\\` se interpreta como carácter de escape")
    lines.append("- Cuando el código fuente tenía `/\\s+/g`, JavaScript lo compilaba como `/s+/g` (sin la barra)")
    lines.append("- El navegador del usuario final recibía `/s+/g` que reemplazaba TODAS las letras 's' con espacio")
    lines.append("")
    lines.append("**Fix aplicado — Doble escape de `\\s` y `\\d` dentro de DASHBOARD_HTML:**")
    lines.append("")
    lines.append("| # | Función | Línea | Antes | Ahora |")
    lines.append("|---|---|---|---|---|")
    lines.append("| 1 | `cleanSnippet` | 997 | `/\\s+/g` (escape simple) | `/\\\\s+/g` (doble escape) ✅ |")
    lines.append("| 2 | `normalizePhoneAR` | 946 | `/^\\d{3,4}15\\d{6,7}$/` | `/^\\\\d{3,4}15\\\\d{6,7}$/` ✅ |")
    lines.append("")
    lines.append("`cleanText` (línea 1005) ya tenía el doble escape correcto desde antes.")
    lines.append("")
    lines.append("**Verificación del deploy:**")
    lines.append("- Código fuente del repo: `/\\\\s+/g` (doble escape, lo que wrangler sube al Worker)")
    lines.append("- HTML servido al navegador: `/\\s+/g` (escape simple, regex correcta que el navegador interpreta)")
    lines.append("- Bug `/s+/g` (sin escape) en código servido: 0 ocurrencias reales (solo en comentarios explicativos)")
    lines.append("- VLM confirmó en screenshot: 'Disputa', 'transferencia', 'Mercedes', 'estado' — todas con 's' visibles ✅")
    lines.append("")
    lines.append("**Nota importante:** Las regex en `runPipelineCron` (líneas 3059, 3290, etc.) NO requieren doble escape porque están fuera del template literal `DASHBOARD_HTML` — son código JS normal del Worker.")
    lines.append("")
    lines.append("### FIX REDISEÑO TWENTY.COM — Black & Zinc + Sliding Drawer + Badges desaturados → DONE")
    lines.append("")
    lines.append("**Rediseño visual sin tocar lógica JS:**")
    lines.append("- **Paleta Black & Zinc:** fondo `#000000`, surfaces `#09090b`, bordes `#27272a`, accent `#6366f1` (índigo premium)")
    lines.append("- **Sliding Drawer:** modal central → panel lateral derecho con animación `slideIn` 0.25s + backdrop blur(4px)")
    lines.append("- **Badges desaturados:** pill redondeados → cuadrados (4px radius) con fondo rgba sutil + border fino")
    lines.append("- **Heat rows:** tintes rgba sutiles sobre negro (no fondos sólidos claros)")
    lines.append("- **Topbar dark:** negro puro + border-bottom zinc (no azul con sombra)")
    lines.append("- **Sidebar dark:** hover surface2, active rgba indigo .1")
    lines.append("- **Tabla dark:** thead surface2, hover surface2, texto blanco")
    lines.append("- **Inputs/textarea dark:** background negro, texto blanco, options dark")
    lines.append("")
    lines.append("**Lógica JS intacta (sin cambios):**")
    lines.append("- Filtros Contacto + Temperatura (Qwen v2.8)")
    lines.append("- Bypass WhatsApp con window.open (Qwen OPCIÓN A)")
    lines.append("- Marca automática 'Contactado' (Qwen v3.1)")
    lines.append("- getUrlSecret() sin prompt (Qwen v2.9)")
    lines.append("- Defaults en 'todos' (Gemini audit v4)")
    lines.append("- sourceFilter case-insensitive (Gemini audit v3)")
    lines.append("- KPI = bandeja (Gemini audit v5)")
    lines.append("- Doble escape \\\\s y \\\\d (Gemini Sabueso v3)")
    lines.append("- Filtro Sabueso Fase 1 + Fase 2 (solo en Python pipeline)")
    lines.append("")
    lines.append("### ✅ FIX ARQUITECTÓNICO GEMINI — Eliminar scraper VentaFe del Edge Cron → DONE")
    lines.append("")
    lines.append("**Problema resuelto:** El dashboard mostraba 92 leads (no 6) con avisos comunes basura (Peugeot 308, Jeep Compass, Chevrolet Agile, etc.)")
    lines.append("")
    lines.append("**Causa raíz:**")
    lines.append("- El filtro Sabueso Fase 1 + Fase 2 está en `classify_and_score()` del **Python pipeline** (generate_payload.py)")
    lines.append("- Pero el **Edge Cron del Worker** (`runPipelineCron` en worker.js) tenía su PROPIO scraper VentaFe que NO pasaba por `classify_and_score`")
    lines.append("- Resultado: el Python generaba 6 leads limpios, pero el Edge Cron sumaba ~86 leads basura al KV")
    lines.append("")
    lines.append("**Filosofía arquitectónica restaurada:**")
    lines.append("> \"Python es el ÚNICO cerebro. El Worker es un proxy puro.\"")
    lines.append("- Python (generate_payload.py): scoring, OSINT, mining, filtros Sabueso, classify_and_score completo")
    lines.append("- Worker (worker.js): solo lee/escribe KV, NO genera leads propios de VentaFe")
    lines.append("")
    lines.append("**Fix aplicado:**")
    lines.append("- Eliminado por completo el bloque `try/catch` del scraper VentaFe en `runPipelineCron` (~70 líneas eliminadas)")
    lines.append("- Variables colgantes eliminadas: `vfPhoneRegex`, `vfPatenteRegex`, `vfHtml`, `vfBlocks`, `vfPhoneCount`")
    lines.append("- El Edge Cron ahora solo trae leads Reddit (con filtro AR estricto + painKwStrict + junkKw)")
    lines.append("- VentaFe queda exclusivamente a cargo del Python pipeline que tiene:")
    lines.append("  - Filtro Sabueso Fase 1 (Pain o Patente)")
    lines.append("  - Filtro Sabueso Fase 2 (afinación fina transferir)")
    lines.append("  - classify_and_score completo")
    lines.append("  - Filtro de Salida post-clasific.ar")
    lines.append("")
    lines.append("**Resultado verificado:**")
    lines.append("- KV purgado y regenerado con workflow Python run #96")
    lines.append("- **7 leads VentaFe limpios** (todos con persona `Vendedor #ID`)")
    lines.append("- **0 leads basura** del Edge Cron (antes ~86)")
    lines.append("- Todos con teléfono y WhatsApp link directo")
    lines.append("")
    lines.append("### ✅ FIX GEMINI TÚNEL — clasific.ar audita VentaFe con patente + boost dinámico → DONE")
    lines.append("")
    lines.append("**Problema resuelto:** Cuello de botella lógico en el pipeline")
    lines.append("- Step 4.5 solo consultaba clasific.ar si `score >= 70`")
    lines.append("- Pero VentaFe preventivos arrancan con `score 40` (Sabueso Fase 2)")
    lines.append("- Como nunca se consultaban, `deuda_clasificar` quedaba en 0")
    lines.append("- Step 4.9 los descartaba por 'sin dolor textual y deuda=0'")
    lines.append("")
    lines.append("**3 parches del Túnel Automático:**")
    lines.append("")
    lines.append("**Parche 1 — Abrir compuerta clasific.ar (Step 4.5):**")
    lines.append("- Antes: `should_enrich = has_patente and score >= 70`")
    lines.append("- Ahora: `should_enrich = has_patente and (score >= 70 or is_vf_lead)`")
    lines.append("- VentaFe con patente se consulta sin importar score")
    lines.append("")
    lines.append("**Parche 2 — Boost dinámico por deuda comprobada:**")
    lines.append("- Si clasific.ar responde `deuda > 0`:")
    lines.append("  - `lead.score = 95` (caliente máximo)")
    lines.append("  - `lead.label = 'real_lead'`")
    lines.append("  - signal `DEUDA_COMPROBADA` inyectada")
    lines.append("  - contador `deuda_comprobada_count` para logging")
    lines.append("")
    lines.append("**Parche 3 — Step 4.9 Filtro de Salida consistente:**")
    lines.append("- Lista de keywords expandida (misma que filtro de admisión Fase 2)")
    lines.append("- Agregada verificación `has_deuda_signal` ('DEUDA_COMPROBADA')")
    lines.append("- Pasa si: dolor textual OR deuda comprobada OR signal DEUDA_COMPROBADA")
    lines.append("")
    lines.append("**⚠️ Hallazgo importante — VentaFe NO muestra patentes en el listado:**")
    lines.append("- Verifiqué el HTML de `ventafe.com.ar/automoviles` → 0 patentes en el listado")
    lines.append("- Las patentes aparecen en la **página de detalle** de cada aviso (ej: `/automoviles/5011468-peugeot-308-allure`)")
    lines.append("- Por eso los 7 leads en KV tienen `patente=''` y `PATENTE_DETECTED=False`")
    lines.append("- El túnel está implementado correctamente pero no se activa porque no hay patentes")
    lines.append("")
    lines.append("**Próxima iteración para activar el túnel al 100%:**")
    lines.append("- Scrapear la página de detalle de cada aviso VentaFe (no solo el listado)")
    lines.append("- Extraer la patente del detalle (campo 'Dominio' o 'Patente')")
    lines.append("- Pasar esa patente al túnel de clasific.ar")
    lines.append("- Implica ~45 requests extra por run (uno por aviso)")
    lines.append("")
    lines.append("### ✅ FIX GEMINI TÚNEL DETALLE — Scraper de página de detalle para extraer patentes → DONE")
    lines.append("")
    lines.append("- Por cada lead VentaFe con teléfono válido, scrapea la página de detalle del aviso")
    lines.append("- Regex SOLO formato Mercosur (AA111AA) — 7 caracteres exactos, sin falsos positivos")
    lines.append("- `time.sleep(0.7)` entre requests (cortesía, evitar bloqueo IP)")
    lines.append("- `timeout=8s` por request (no cuelga el pipeline)")
    lines.append("- ~45 leads × 0.7s = ~30s extra al pipeline (dentro del límite de 10min)")
    lines.append("- **Hallazgo:** VentaFe NO muestra patentes NI en el detalle del aviso. Scraper funciona pero no encuentra patentes.")
    lines.append("")
    lines.append("### ✅ FIX GEMINI SABUESO Fase 3 — Solo dolor real explícito, eliminar preventivas sin patente → DONE")
    lines.append("")
    lines.append("- Eliminadas keywords preventivas del filtro de admisión ('sin deuda', 'sin multas', 'papeles al día')")
    lines.append("- Solo se admite VentaFe si tiene dolor REAL explícito (multa, deuda, sin 08, titular fallecido, etc.) o patente")
    lines.append("- Regex con word boundaries para evitar que 'traba' matchee 'trabajo/trabajar'")
    lines.append("- Exclusión de contexto negativo: 'sin deuda, multas' no matchea como dolor")
    lines.append("- **Resultado:** 0 leads (VentaFe no tiene avisos con dolor real explícito)")
    lines.append("")
    lines.append("### ✅ FIX GEMINI VÍA A+B — Dolor registral + Triangulación cross-platform ML → DONE")
    lines.append("")
    lines.append("**Vía A — Filtro de Dolor Registral:**")
    lines.append("- Cambio de dolor genérico (multa/deuda) a dolor REGISTRAL específico:")
    lines.append("  - 'sin 08', '08 vencido', '08 firmado en blanco'")
    lines.append("  - 'titular fallecido', 'titular inubicable', 'titular no firma'")
    lines.append("  - 'sucesión', 'poseedor', 'denuncia de compra', 'tarjeta rosa'")
    lines.append("  - 'embargo', 'inhibición', 'bloqueado'")
    lines.append("- **Resultado:** 0 leads (vendedores de VentaFe no declaran problemas registrales)")
    lines.append("")
    lines.append("**Vía B — Triangulación Cross-Platform Matcher:**")
    lines.append("- Nueva función `try_triangulate_plate(brand, model, mileage, location)`")
    lines.append("- Busca publicación espejo en MercadoLibre por marca+modelo+kilometraje")
    lines.append("- Extrae patente de Q&A donde compradores preguntan y vendedores responden")
    lines.append("- Solo se ejecuta si VentaFe no tiene patente (no gastar cuota innecesaria)")
    lines.append("")
    lines.append("### ✅ FIX GEMINI HÍBRIDO — VentaFe preventivo + FB dorking + etiquetado claro → DONE")
    lines.append("")
    lines.append("**Mejora 1 — VentaFe Híbrido (clasify_and_score):**")
    lines.append("- Caso 1: Dolor registral explícito → score +40, signal `DOLOR_EXPLICITO_REGISTRAL`")
    lines.append("- Caso 2: Preventivo ('papeles al día', 'listo para transferir') → score +15, signal `PREVENTIVO_A_VERIFICAR`")
    lines.append("- Caso 3: No menciona nada → descartar (ruido)")
    lines.append("- Sergio sabe cómo abordar cada lead según la etiqueta")
    lines.append("")
    lines.append("**Mejora 2 — Dorking Facebook grupos A+B sin cookies:**")
    lines.append("- Grupo A: `site:facebook.com/groups/276074287942602` multa/fotomulta + teléfonos")
    lines.append("- Grupo B: `site:facebook.com/groups/1314803566577708` debe/deuda/08 + teléfonos")
    lines.append("- Los buscadores indexan posts de grupos públicos → extraer sin cookies")
    lines.append("")
    lines.append("**Mejora 3 — Etiquetado problem_sum claro:**")
    lines.append("- `DOLOR_EXPLICITO_REGISTRAL` → 'Trámite registral complejo detectado'")
    lines.append("- `PREVENTIVO_A_VERIFICAR` → 'Preventivo — Verificación de deuda sugerida'")
    lines.append("- Step 4.9 sincronizado: pasa si tiene signal válida OR deuda OR patente")
    lines.append("")
    lines.append("**Resultado:** 14 leads VentaFe preventivos con teléfono + WhatsApp directo")
    lines.append("")
    lines.append("### ✅ FIX QWEN — Apify FB scraper con 2 grupos + APIFY_TOKEN refrescado → DONE")
    lines.append("")
    lines.append("- **APIFY_TOKEN refrescado** con token nuevo del user `zYZdh5dNA6AhMa7GO`")
    lines.append("- **Grupo A** (`276074287942602` — Defensas contra Multas AR): ya estaba")
    lines.append("- **Grupo B** (`1314803566577708` — Venta Santa Fe y Alrededores): NUEVO")
    lines.append("- Apify run `lwk3PTxMozPIBqsNi` → SUCCEEDED, 20 posts extraídos del Grupo B")
    lines.append("- Posts enviados al KV via `/api/apify-webhook` → 20 leads Facebook mergeados")
    lines.append("- **Total KV:** 36 leads (14 VentaFe con WhatsApp + 20 Facebook + 2 Reddit)")
    lines.append("")
    lines.append("### ✅ FIX QWEN — Filtro estricto dolor + scoring dinámico en apify-webhook → DONE")
    lines.append("")
    lines.append("**Problema:** `/api/apify-webhook` ingería todo lo que Apify devolvía sin filtro, hardcodeaba `score:50` y mandaba al KV. Por eso había heladeras, muebles y ventas genéricas en el dashboard.")
    lines.append("")
    lines.append("**3 cambios en el webhook:**")
    lines.append("")
    lines.append("**1. Filtro estricto de dolor vehicular (PAIN_KW):**")
    lines.append("- Regex que exige al menos una keyword: multa, fotomulta, infracción, libre deuda, transferencia, transferir, patente, 08, cédula, veraz, registro automotor, juez de faltas, peaje, deuda, vencimiento, prescripción, papeles al día, listo para transferir, sin deuda, titular")
    lines.append("- Si no matchea → `continue` (descartar inmediatamente)")
    lines.append("")
    lines.append("**2. Scoring dinámico (no hardcodear 50):**")
    lines.append("- Base: 40")
    lines.append("- multa/fotomulta: +20")
    lines.append("- transferencia/transferir/08: +15")
    lines.append("- deuda/libre deuda: +15")
    lines.append("- tiene teléfono o email: +20")
    lines.append("- Max: 100")
    lines.append("")
    lines.append("**3. Umbral mínimo:** `score < 50` → descartar")
    lines.append("")
    lines.append("**Resultado verificado:**")
    lines.append("- 20 posts de FB re-procesados con el nuevo filtro → `received: 0, filtered_out: 20`")
    lines.append("- Los 20 posts NO mencionaban dolor vehicular (heladeras, muebles, ventas genéricas) → todos descartados")
    lines.append("- KV purgado y regenerado: **14 leads VentaFe preventivos** (limpios, sin basura FB)")
    lines.append("- Solo posts de FB con dolor vehicular explícito llegarán al KV en el futuro")
    lines.append("")
    lines.append("### ✅ FIX QWEN v2 — FB intent scoring + VentaFe preventivos capados/filtrados → DONE")
    lines.append("")
    lines.append("**FIX 1 — apify-webhook con INTENT_KW + scoring adaptado:**")
    lines.append("- `INTENT_KW`: detecta consultas/reclamos (consultar, ayuda, recomiendan, se puede, abonar, defender)")
    lines.append("- `PAIN_KW` ampliado: forzar barrera, reclamo, evidencia, foto")
    lines.append("- Scoring: base 30, +25 multa, +20 transferencia, +20 deuda, +15 intent, +20 contacto, +15 patente")
    lines.append("- Umbral: < 45 → descartar")
    lines.append("")
    lines.append("**FIX 2A — Capar score de preventivos a 42:**")
    lines.append("- Preventivos sin `DEUDA_COMPROBADA` → score capado a 42 (nunca calientes)")
    lines.append("- Preventivos puros sin patente ni dolor → `return None` (descartar)")
    lines.append("")
    lines.append("**FIX 2B — Endurecer Step 4.9:**")
    lines.append("- Solo pasan VentaFe con `DOLOR_EXPLICITO_REGISTRAL` o `DEUDA_COMPROBADA`")
    lines.append("- Preventivos solos ya no pasan el filtro de salida")
    lines.append("")
    lines.append("### ✅ FIX ANTI-SPAM + ANTI-DUPLICADOS en apify-webhook → DONE")
    lines.append("")
    lines.append("- `SPAM_KW`: bloquea posts de venta de cursos/seminarios (seminario, curso, asincrónico, pack incluye)")
    lines.append("- `seenAuthors`: 1 post por autor (elimina 6 duplicados de Roberto López Freijo)")
    lines.append("- Resultado: de 20 posts → 11 leads limpios (9 descartados: 3 sin dolor + 6 spam)")
    lines.append("")
    lines.append("### ✅ FIX SIMON — Filtrar ofertas de servicios gestoriales (competidores) → DONE")
    lines.append("")
    lines.append("- `SERVICE_OFFER_KW`: bloquea posts de gestores/competidores que OFRECEN servicios")
    lines.append("  - 'elimino multas', 'saco turnos', 'hago informes'")
    lines.append("  - 'gestoría', 'gestor automotor'")
    lines.append("  - 'ofrezco mis servicios', 'mis servicios'")
    lines.append("  - 'consultanos', 'defendemos tus derechos'")
    lines.append("- Jess Borella (gestora que publicitaba 'ELIMINO MULTAS') → filtrada")
    lines.append("- Resultado: **10 leads limpios**, todos personas CON problemas reales, 0 competidores")
    lines.append("")
    lines.append("### 📊 Estado final del KV — 10 leads Facebook Grupo A con dolor real")
    lines.append("")
    lines.append("| # | Usuario | Score | Dolor |")
    lines.append("|---|---|---|---|")
    lines.append("| 1 | Benitez Brandon | 100 | Moto con infracción, forzar barrera, sin contacto vendedor |")
    lines.append("| 2 | Jorge Cadiboni | 90 | 3 multas de moto transferida, 3 veces descargo |")
    lines.append("| 3 | Juan Lotito | 75 | Camioneta con 2 multas del dueño anterior |")
    lines.append("| 4 | Vlad Gold | 70 | Multa del primer dueño que falleció |")
    lines.append("| 5 | Adolfo Giraudo | 65 | Vende taxi Toyota Corolla |")
    lines.append("| 6-10 | 5 consultas | 45-55 | Multas, descargos, prescripción, exceso velocidad |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📜 Git Log (últimos 20 commits)")
    lines.append("")
    lines.append("```")
    lines.append(log)
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")

    for i, (rel, lang, desc) in enumerate(FILES, 1):
        content = get_repo_file(rel)
        lines.append(f"## {i}. `{rel}`")
        lines.append("")
        lines.append(f"**Descripción:** {desc}  ")
        lines.append("")
        lines.append(f"```{lang}")
        lines.append(content.rstrip())
        lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Footer
    lines.append("## 🔑 Secrets / Variables Necesarias")
    lines.append("")
    lines.append("| Lugar | Variable | Valor actual | Uso |")
    lines.append("|-------|----------|--------------|-----|")
    lines.append("| Cloudflare Worker secret | `INGEST_SECRET` | `LEGACY_SECRET_REMOVED` | Auth X-Webhook-Secret en /api/ingest y otros |")
    lines.append("| Cloudflare Worker secret | `APIFY_TOKEN` | (legacy) | Facebook scraper + WA validator (no se usa más desde OPCIÓN A) |")
    lines.append("| Cloudflare Worker secret | `CLASIFICAR_WEBHOOK_SECRET` | (seteado) | Webhook de clasific.ar |")
    lines.append("| Cloudflare Worker secret | `FB_COOKIES` | (seteado) | Cookies Facebook para scraper |")
    lines.append("| GitHub Actions secret | `INGEST_SECRET` | `LEGACY_SECRET_REMOVED` | Debe matchear Worker INGEST_SECRET |")
    lines.append("| GitHub Actions secret | `ZAI_API_KEY` | (seteado) | z-ai web_search SDK |")
    lines.append("| GitHub Actions env | `WORKER_URL` | `https://leadx.simondalmasso44.workers.dev` | URL del Worker |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 🚀 Cómo reproducir un deploy")
    lines.append("")
    lines.append("```bash")
    lines.append("# 1. Clonar repo")
    lines.append("git clone https://github.com/simonkey888/Leadx.git")
    lines.append("cd Leadx")
    lines.append("")
    lines.append("# 2. Deploy Cloudflare Worker")
    lines.append("npx wrangler deploy \\")
    lines.append("  --name leadx \\")
    lines.append("  --account-id b21fa81d12acb663798f9f7c51801955")
    lines.append("")
    lines.append("# 3. Setear secrets del Worker")
    lines.append("echo 'LEGACY_SECRET_REMOVED' | npx wrangler secret put INGEST_SECRET")
    lines.append("")
    lines.append("# 4. Trigger manual del workflow")
    lines.append("curl -X POST \\")
    lines.append("  -H 'Authorization: Bearer $GH_TOKEN' \\")
    lines.append("  -H 'Accept: application/vnd.github+json' \\")
    lines.append("  https://api.github.com/repos/simonkey888/Leadx/actions/workflows/radar-cron.yml/dispatches \\")
    lines.append("  -d '{\"ref\":\"main\"}'")
    lines.append("")
    lines.append("# 5. Verificar")
    lines.append("curl 'https://leadx.simondalmasso44.workers.dev/api/leads?key=LEGACY_SECRET_REMOVED' | python3 -m json.tool | head -30")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"**Bundle generado automáticamente el {now} para auditoría de Kimi.**")
    lines.append("")
    lines.append("Próximos pasos sugeridos para Kimi auditar:")
    lines.append("1. Performance del scraper VentaFe (100 bloques, 16-17 válidos — ¿se puede subir a 30+?)")
    lines.append("2. Cruce de patentes VentaFe con clasific.ar (free 200/mes) para detectar deuda real")
    lines.append("3. Encoding de títulos Reddit ('tran ferencia' → 'transferencia' — entities HTML)")
    lines.append("4. Limpieza de leads basura del KV (los que no tienen VentaFe ni teléfono)")
    lines.append("5. Minería de contactos en perfil de Reddit users (Linktree Hunter)")
    lines.append("6. Validar que el webhook de Apify (`/api/whatsapp-webhook`) efectivamente reciba resultados")
    lines.append("7. Activar `/api/apify-facebook` con cookies frescas para traer leads de grupos FB")
    lines.append("8. Scoring: ¿conviene un boost extra para leads con WhatsApp link directo (wa.me)?")
    lines.append("9. El endpoint `/api/shadow-osint` (Linktree Hunter) — ¿está siendo llamado por algún cron?")
    lines.append("10. Anti-junk filter para portugués/Brasil — ¿sigue siendo efectivo con los nuevos leads?")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK → {OUT}")
    print(f"Tamaño: {OUT.stat().st_size:,} bytes ({OUT.stat().st_size/1024:.1f} KB)")
    print(f"Líneas totales: {len(lines):,}")

if __name__ == "__main__":
    build()
