import{useCallback,useEffect,useMemo,useRef,useState}from"react";import{LockKeyhole,LogOut,RefreshCw,X}from"lucide-react";import type{Lead,SessionInfo,Vertical}from"./types";import{checkSession,continueSession,fetchLeads,login,logout,SessionExpiredError}from"./lib/api";import{clearCrmState,mergeCrmState}from"./lib/storage";import{demoByVertical}from"./demo-leads";import{purgeRealSessionState}from"./lib/session-state";import{Kpis}from"./components/Kpis";import{EMPTY_FILTERS,Filters,type FilterState}from"./components/Filters";import{LeadTable}from"./components/LeadTable";import{LeadDetail}from"./components/LeadDetail";
const parseVertical=():Vertical=>new URLSearchParams(location.search).get("linea")==="repuestos_agricolas"?"repuestos_agricolas":"fotomultas";
const REAL_SESSION: SessionInfo = { authenticated: true, mode: "real" };
export default function App(){const[vertical,setVertical]=useState<Vertical>(parseVertical);const[leads,setLeads]=useState<Lead[]>(demoByVertical(parseVertical()));const[session,setSession]=useState<SessionInfo>({authenticated:false,mode:"demo"});const[loading,setLoading]=useState(true);const[password,setPassword]=useState("");const[loginOpen,setLoginOpen]=useState(false);const[loginError,setLoginError]=useState("");const[selectedLead,setSelectedLead]=useState<Lead|null>(null);const[search,setSearch]=useState("");const[filters,setFilters]=useState<FilterState>(EMPTY_FILTERS);const[sort,setSort]=useState("recent");const[idleWarning,setIdleWarning]=useState(false);const[notice,setNotice]=useState("");const lastActivity=useRef(Date.now()),lastTouch=useRef(0),absolute=useRef(0),sessionRef=useRef(session);useEffect(()=>{sessionRef.current=session},[session]);
 const restoreDemo=useCallback((message="")=>{const safe=purgeRealSessionState(demoByVertical(vertical),clearCrmState);setLeads(safe.leads);setSession(safe.session);setSelectedLead(null);setLoginOpen(false);setIdleWarning(false);setPassword("");setNotice(message);document.body.classList.remove("filters-open")},[vertical]);
 const endSession=useCallback((message:string)=>{restoreDemo(message);void logout().catch(()=>{})},[restoreDemo]);
 const load=useCallback(async(auth:boolean,userActivity=false,v:Vertical=vertical)=>{setLoading(true);try{const result=await fetchLeads(auth,userActivity,v);setLeads(auth&&!result.isDemo?mergeCrmState(result.leads):result.leads)}catch(e){if(e instanceof SessionExpiredError)endSession("Tu sesión terminó. Volvimos al modo demo.")}finally{setLoading(false)}},[vertical,endSession]);
 useEffect(()=>{void(async()=>{const s=await checkSession();setSession(s);if(s.authenticated){lastActivity.current=(s.idleExpiresAt||Date.now()+1200000)-1200000;absolute.current=s.absoluteExpiresAt||Date.now()+28800000}await load(s.authenticated,false,vertical)})()},[]);
 useEffect(()=>{const onPop=()=>switchVertical(parseVertical(),false);addEventListener("popstate",onPop);return()=>removeEventListener("popstate",onPop)},[session.authenticated]);
 useEffect(()=>{if(!session.authenticated)return;const timer=setInterval(()=>{const idle=Date.now()-lastActivity.current;if(Date.now()>=absolute.current||idle>=1200000)endSession(idle>=1200000?"Tu sesión terminó por inactividad. Volvimos al modo demo.":"Tu sesión alcanzó el máximo de 8 horas. Volvimos al modo demo.");else if(idle>=1080000)setIdleWarning(true)},1000);return()=>clearInterval(timer)},[session.authenticated,endSession]);
 useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSelectedLead(null);setLoginOpen(false);document.body.classList.remove("filters-open")}};addEventListener("keydown",esc);return()=>removeEventListener("keydown",esc)},[]);
 const activity=useCallback(()=>{if(!sessionRef.current.authenticated)return;const now=Date.now();lastActivity.current=now;setIdleWarning(false);if(now-lastTouch.current<60000)return;lastTouch.current=now;void continueSession().then(s=>{if(s.absoluteExpiresAt)absolute.current=s.absoluteExpiresAt}).catch(()=>endSession("Tu sesión terminó. Volvimos al modo demo."))},[endSession]);
 function switchVertical(v:Vertical,push=true){setVertical(v);setSelectedLead(null);setSearch("");setFilters(EMPTY_FILTERS);if(push)history.pushState({},"",`?linea=${v}`);void load(session.authenticated,false,v)}
 async function submitLogin(){setLoginError("");const r=await login(password);if(!r.ok){setLoginError(r.error||"Contraseña incorrecta");return}const checked=await checkSession();const s={...REAL_SESSION,...checked};setSession(s);lastActivity.current=Date.now();lastTouch.current=Date.now();absolute.current=s.absoluteExpiresAt||Date.now()+28800000;setLoginOpen(false);setPassword("");await load(true,true)}
 const filtered=useMemo(()=>leads.filter(l=>{const d=Object.values(l.vertical_data||{}).join(" ");const hay=`${l.name||l.persona||""} ${l.province||l.provincia||""} ${l.phone||l.telefono||""} ${d}`.toLowerCase();if(search.trim()&&!hay.includes(search.trim().toLowerCase()))return false;if(filters.status&&(l._status||l.status)!==filters.status)return false;if(filters.priority&&(l._priority||l.priority)!==filters.priority)return false;if(filters.province&&(l.province||l.provincia)!==filters.province)return false;if(filters.channel&&(l.channel||l.source_label)!==filters.channel)return false;if(filters.assigned&&(l.assigned_to||l.owner||"Sin asignar")!==filters.assigned)return false;if(filters.specific&&!d.toLowerCase().includes(filters.specific.toLowerCase()))return false;return true}).sort((a,b)=>sort==="name"?String(a.name||a.persona).localeCompare(String(b.name||b.persona),"es"):sort==="priority"?Number(b.score)-Number(a.score):new Date(String(b.created_at||b.fecha_iso)).getTime()-new Date(String(a.created_at||a.fecha_iso)).getTime()),[leads,search,filters,sort]);
 return <main className="app"><header className="app-header"><div><h1>LeadX</h1><p>CRM comercial simple</p></div><div className="app-actions"><span className={`mode-badge ${session.authenticated?"real":"demo"}`}>{session.authenticated?"Datos reales":"Modo demo"}</span>{session.authenticated?<><button className="icon-button" onClick={()=>load(true,true)} aria-label="Actualizar"><RefreshCw size={17}/></button><button className="btn" onClick={()=>endSession("Cerraste la sesión. Volvimos al modo demo.")}><LogOut size={16}/>Salir</button></>:<><form className="desktop-login" onSubmit={e=>{e.preventDefault();void submitLogin()}}><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn btn--primary">Entrar</button></form><button className="btn mobile-login" onClick={()=>setLoginOpen(true)}><LockKeyhole size={16}/>Datos reales</button></>}</div></header>{notice&&<p className="notice">{notice}</p>} {!session.authenticated&&<p className="demo-caption">Datos ficticios para explorar el CRM</p>}
 <nav className="vertical-switch" aria-label="Línea comercial"><button className={vertical==="fotomultas"?"active":""} onClick={()=>switchVertical("fotomultas")}>Fotomultas</button><button className={vertical==="repuestos_agricolas"?"active":""} onClick={()=>switchVertical("repuestos_agricolas")}>Repuestos agrícolas</button></nav><section className="workspace"><div className="section-title"><div><small>Línea comercial</small><h2>{vertical==="fotomultas"?"Fotomultas":"Repuestos agrícolas"}</h2></div><span>{filtered.length} resultados</span></div><Kpis leads={leads}/><Filters leads={leads} vertical={vertical} search={search} setSearch={setSearch} filters={filters} setFilters={setFilters} sort={sort} setSort={setSort} onActivity={activity}/>{loading&&leads.length===0?<div className="empty">Cargando…</div>:<LeadTable leads={filtered} vertical={vertical} selectedId={selectedLead?.id} onSelect={setSelectedLead} onActivity={activity}/>}</section>
 {selectedLead&&<LeadDetail lead={selectedLead} onClose={()=>setSelectedLead(null)} onActivity={activity}/>} {loginOpen&&<div className="sheet-layer" onMouseDown={e=>{if(e.target===e.currentTarget)setLoginOpen(false)}}><form className="login-sheet" onSubmit={e=>{e.preventDefault();void submitLogin()}}><header><h2>Desbloquear datos reales</h2><button type="button" className="icon-button" onClick={()=>setLoginOpen(false)}><X/></button></header><label>Contraseña<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{loginError&&<p className="error">{loginError}</p>}<button className="btn btn--primary">Ingresar</button></form></div>} {idleWarning&&<div className="modal-layer"><div className="session-warning" role="alertdialog"><h2>Tu sesión se cerrará por inactividad.</h2><button className="btn btn--primary" onClick={()=>void continueSession().then(()=>{lastActivity.current=Date.now();setIdleWarning(false)}).catch(()=>endSession("Tu sesión terminó por inactividad. Volvimos al modo demo."))}>Continuar sesión</button><button className="btn" onClick={()=>endSession("Cerraste la sesión. Volvimos al modo demo.")}>Salir ahora</button></div></div>}</main>}
