import type { Lead } from "./types";

const now = Date.now();
const ago = (milliseconds: number) => new Date(now - milliseconds).toISOString();

export const DEMO_LEADS: Lead[] = [
  { id: "demo_001", score: 95, persona: "Carlos Demo", provincia: "Santa Fe", platform: "Foro ficticio", source: "demo", source_label: "Foro ficticio", title: "Multa de moto comprada usada", snippet: "Compré una moto usada y apareció una multa anterior. ¿Cómo puedo regularizarla?", vehiculo: "moto", fecha_iso: ago(6 * 3600000), _status: "Nuevo", _priority: "Alta", _isDemo: true },
  { id: "demo_002", score: 88, persona: "María Ejemplo", provincia: "CABA", platform: "Consulta ficticia", source: "demo", source_label: "Consulta ficticia", title: "Transferencia bloqueada por multas", snippet: "La transferencia quedó bloqueada por infracciones que no reconozco.", vehiculo: "moto", fecha_iso: ago(2 * 3600000), _status: "Nuevo", _priority: "Alta", _isDemo: true },
  { id: "demo_003", score: 75, persona: "Juan Prueba", provincia: "Buenos Aires", platform: "Foro ficticio", source: "demo", source_label: "Foro ficticio", title: "Multas del titular anterior", snippet: "La camioneta conserva dos multas del dueño anterior y necesito transferirla.", vehiculo: "camioneta", fecha_iso: ago(86400000), _status: "Contactado", _priority: "Alta", _isDemo: true },
  { id: "demo_004", score: 70, persona: "Ana Ficticia", provincia: "Entre Ríos", platform: "Consulta ficticia", source: "demo", source_label: "Consulta ficticia", title: "Infracción asociada al primer dueño", snippet: "Apareció una infracción del primer titular y no sé cómo presentar el descargo.", vehiculo: "auto", fecha_iso: ago(4 * 3600000), _status: "Nuevo", _priority: "Media", _isDemo: true },
  { id: "demo_005", score: 65, persona: "Pedro Muestra", provincia: "CABA", platform: "Foro ficticio", source: "demo", source_label: "Foro ficticio", title: "Fotomulta por velocidad", snippet: "Recibí una fotomulta por una diferencia mínima de velocidad permitida.", vehiculo: "auto", fecha_iso: ago(12 * 3600000), _status: "En gestión", _priority: "Media", _isDemo: true },
  { id: "demo_006", score: 55, persona: "Lucía Ficticia", provincia: "Misiones", platform: "Consulta ficticia", source: "demo", source_label: "Consulta ficticia", title: "Prescripción de radar móvil", snippet: "Necesito saber qué documentación revisar para evaluar la prescripción.", vehiculo: "auto", fecha_iso: ago(18 * 3600000), _status: "Nuevo", _priority: "Media", _isDemo: true },
  { id: "demo_007", score: 50, persona: "Roberto Demo", provincia: "Santa Fe", platform: "Foro ficticio", source: "demo", source_label: "Foro ficticio", title: "Dominio cargado incorrectamente", snippet: "La infracción parece corresponder a otro vehículo con un dominio similar.", vehiculo: "auto", fecha_iso: ago(2 * 86400000), _status: "Cerrado", _priority: "Baja", _isDemo: true },
  { id: "demo_008", score: 45, persona: "Patricia Ejemplo", provincia: "Corrientes", platform: "Consulta ficticia", source: "demo", source_label: "Consulta ficticia", title: "Infracciones ausentes en la consulta", snippet: "Una oficina informa deuda pero el portal de consulta no muestra infracciones.", fecha_iso: ago(3 * 86400000), _status: "Revisado", _priority: "Baja", _isDemo: true },
  { id: "demo_009", score: 40, persona: "Diego Prueba", provincia: "Buenos Aires", platform: "Foro ficticio", source: "demo", source_label: "Foro ficticio", title: "Descargo por multas antiguas", snippet: "Quiero ordenar varias multas antiguas antes de iniciar una transferencia.", vehiculo: "moto", fecha_iso: ago(5 * 86400000), _status: "Descartado", _priority: "Baja", _isDemo: true },
  { id: "demo_010", score: 35, persona: "Sandra Prueba", provincia: "CABA", platform: "Consulta ficticia", source: "demo", source_label: "Consulta ficticia", title: "VTV y regularización", snippet: "Necesito regularizar VTV e infracciones antes de renovar documentación.", vehiculo: "auto", fecha_iso: ago(7 * 86400000), _status: "Nuevo", _priority: "Baja", _isDemo: true },
  { id: "demo_011", score: 80, persona: "Fernando Demo", provincia: "Santa Fe", platform: "Foro ficticio", source: "demo", source_label: "Foro ficticio", title: "Infracción en ruta provincial", snippet: "Recibí un acta en una ruta provincial y necesito revisar su información.", vehiculo: "camioneta", fecha_iso: ago(8 * 3600000), _status: "Nuevo", _priority: "Alta", _isDemo: true },
  { id: "demo_012", score: 60, persona: "Carolina Muestra", provincia: "Entre Ríos", platform: "Consulta ficticia", source: "demo", source_label: "Consulta ficticia", title: "Retención con grúa municipal", snippet: "El vehículo fue retirado por una grúa y necesito identificar los pasos de regularización.", vehiculo: "auto", fecha_iso: ago(14 * 3600000), _status: "Esperando respuesta", _priority: "Media", _isDemo: true },
];
