// ════════════════════════════════════════════════════════════
// DEMO LEADS — completely fictitious, no real data
// Used in PUBLIC_MODE only. Never mixed with real leads.
// ════════════════════════════════════════════════════════════

import type { Lead } from "./types";

export const DEMO_LEADS: Lead[] = [
  {
    id: "demo_001",
    score: 95,
    persona: "Carlos Demo",
    provincia: "Santa Fe",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Multa de moto comprada usada",
    snippet: "Hola, compré una moto usada y ahora me apareció una multa de enero. ¿Qué puedo hacer?",
    vehiculo: "moto",
    fecha_iso: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    fb_username: "demo_user_001",
    _status: "Nuevo",
  },
  {
    id: "demo_002",
    score: 88,
    persona: "María Ejemplo",
    provincia: "CABA",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "3 multas de tránsito transferidas",
    snippet: "Tengo 3 multas de una moto que transferí hace más de un año. Ya hice descargo 3 veces.",
    vehiculo: "moto",
    fecha_iso: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    fb_username: "demo_user_002",
    _status: "Nuevo",
  },
  {
    id: "demo_003",
    score: 75,
    persona: "Juan Prueba",
    provincia: "Buenos Aires",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Camioneta con multas del dueño anterior",
    snippet: "Compré una camioneta que tenía 2 multas del dueño anterior, él se negó a pagarlas.",
    vehiculo: "camioneta",
    fecha_iso: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    fb_username: "demo_user_003",
    telefono_publico: "+5491134567890",
    _status: "Contactado",
  },
  {
    id: "demo_004",
    score: 70,
    persona: "Ana Test",
    provincia: "Entre Ríos",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Multa del primer dueño fallecido",
    snippet: "Consulta sobre una multa del primer dueño del auto, falleció el hombre.",
    vehiculo: "auto",
    fecha_iso: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    fb_username: "demo_user_004",
    _status: "Nuevo",
  },
  {
    id: "demo_005",
    score: 65,
    persona: "Pedro Sample",
    provincia: "CABA",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Exceso de velocidad CABA",
    snippet: "Me llegó una multa de CABA por exceso de velocidad 84km/h max 80.",
    vehiculo: "auto",
    fecha_iso: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    telefono_publico: "+5491134567890",
    _status: "En gestión",
  },
  {
    id: "demo_006",
    score: 55,
    persona: "Lucía Mock",
    provincia: "Misiones",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Multa de radar móvil ¿prescribe?",
    snippet: "Las multas de radar móvil prescriben a los 3 años? Depende de la jurisdicción?",
    vehiculo: "auto",
    fecha_iso: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    fb_username: "demo_user_006",
    _status: "Nuevo",
  },
  {
    id: "demo_007",
    score: 50,
    persona: "Roberto Demo",
    provincia: "Santa Fe",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Patente mal cargada en multa",
    snippet: "Me apareció una multa radicada en La Plata por exceso de velocidad, cargaron mal mi patente.",
    vehiculo: "auto",
    fecha_iso: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    fb_username: "demo_user_007",
    _status: "Cerrado",
  },
  {
    id: "demo_008",
    score: 45,
    persona: "Patricia Ejemplo",
    provincia: "Corrientes",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Páginas de consulta no muestran infracciones",
    snippet: "Por qué en las páginas de consulta de infracciones no aparecen si hay alguna.",
    fecha_iso: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    fb_username: "demo_user_008",
    _status: "Nuevo",
  },
  {
    id: "demo_009",
    score: 40,
    persona: "Diego Prueba",
    provincia: "Buenos Aires",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Descargo por 3 multas del 2023",
    snippet: "Se puede hacer algún descargo? Todas son del 2023 la última por exceso de velocidad.",
    vehiculo: "moto",
    fecha_iso: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
    _status: "Descartado",
  },
  {
    id: "demo_010",
    score: 35,
    persona: "Sandra Test",
    provincia: "CABA",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Consulta sobre VTV y multas",
    snippet: "Tengo la VTV vencida, ¿puedo tener problemas para renovar el registro?",
    vehiculo: "auto",
    fecha_iso: new Date(Date.now() - 7 * 86400 * 1000).toISOString(),
    telefono_publico: "+5491134567890",
    _status: "Nuevo",
  },
  {
    id: "demo_011",
    score: 80,
    persona: "Fernando Demo",
    provincia: "Santa Fe",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Ruta provincial, multa de policía caminera",
    snippet: "Policía Caminera en ruta provincial Santa Fe, no sé el monto de la multa.",
    vehiculo: "camioneta",
    fecha_iso: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    fb_username: "demo_user_011",
    _status: "Nuevo",
  },
  {
    id: "demo_012",
    score: 60,
    persona: "Carolina Sample",
    provincia: "Entre Ríos",
    platform: "Facebook",
    source: "facebook_apify",
    source_label: "Facebook",
    title: "Multa de grúa municipal",
    snippet: "Me llevaron el auto con grúa municipal, ¿eso cuenta como multa de tránsito?",
    vehiculo: "auto",
    fecha_iso: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    fb_username: "demo_user_012",
    _status: "Nuevo",
  },
];
